# set terminal mode to xterm-256color
set -g default-terminal "xterm-256color"

# prefix to Ctrl+A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file with r
bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded!"

# switch panes using alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# enable mouse
set -g mouse on

# incrase history limit to 5k lines (default is 2k)
set-option -g history-limit 5000

# numbering windows/panes from 1 (default is 0)
set -g base-index 1
setw -g pane-base-index 1

# swapping windows with < >
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# colors
set -g status-bg cyan
