[font]
normal = { family="JetBrainsMono Nerd Font" }
size = 14

[colors.primary]
background = '#1e1c31'
foreground = '#cbe1e7'

[colors.cursor]
text = '#000000'
cursor = '#47fff6'

[colors.normal]
black   = '#141228'
red     = '#ff5458'
green   = '#62d196'
yellow  = '#ffb378'
blue    = '#65b2ff'
magenta = '#906cff'
cyan    = '#63f2f1'
white   = '#a6b3cc'

[colors.bright]
black   = '#565575'
red     = '#ff8080'
green   = '#95ffa4'
yellow  = '#ffe9aa'
blue    = '#91ddff'
magenta = '#c991e1'
cyan    = '#aaffe4'
white   = '#cbe3e7'

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste" },
    { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance"}
]

